TS_AUTHKEY: ENC[AES256_GCM,data:mg0/S2/MyPDUUQTkycqTup1hRCgXjwzMwZmlVANRSGxlGlUTjch/LKGXa8Mx29SrlDk0QcnEbAb8U9rV/Y0=,iv:JG+bNKw+cXm2sAIdPJD5lLgoVpBzRVvrcwyHTIs7bII=,tag:oduvGzFwC6z+3nFE1NOf2w==,type:str]
TS_ROUTES: ENC[AES256_GCM,data:X7wq/U6NGHEp2i6RlZk=,iv:Km8+0gOUA/AFDzIoS/NCeG+UVgIHhh6ktHhxKhXJvaA=,tag:MUxU8TiUcedvsSfMO1vIPQ==,type:str]
TS_EXTRA_ARGS: ENC[AES256_GCM,data:rMmoERxs4qKjkSILGY2WTYjT+2U/,iv:LPBN7cWCVlREJh7X/+RYWWDlpcMy8TiqCw3xKIuKH7A=,tag:xKqVkoMEKrLHL63h0QgjsA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ0ZkbTNQU3VtOHR0K2Z6
            NnkybUs1TE45bkE0VnVzNGJZZEF6YitVSGhzCjNWK1ByTzFHTXlLQVdRZ1U4U2hs
            OVFRK1Q0TGgzbjB1Um9nTTZGamtUbE0KLS0tIDgvUnN4TkRpMHN1QVRPck8zM29v
            M2dzeVhTTDZJc3NSZ1U4bS9tNjJLL2cKFtq/j41DdPIlLGfXRIvBxRq1fGuKpw5I
            0NET1qCLNLlGb8jcw3ArSB1oT50invk4cFZqhT/AnTy5rfi6iQlzEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ft5t2uyrll4klez79haqfcfth0nt6kunx8yeta93uu63vwum2dusy72gqn
    lastmodified: "2026-10-02T14:13:04Z"
    mac: ENC[AES256_GCM,data:P1cgq7Z+9UUdbc+PcNd10xuxQzo3X66WI40hbJ0BzuTh6bsMZOZkWtuQO4p+cSStLWGj559OmThCIWfVNwzJsG3b7e+iI1H2v0KsxO8nFfjs79j0pZwAY8hLGmDipGQZ9ccQoUOgb13J8RjbxH8P5ssfwCJ63Bna+j2epUmQuzU=,iv:ovCjOo+ghQMJjMFsRpTZtn9ustQuAwarM650HteDGZg=,tag:jjNyzcV7YFaQl8uhCmhxTQ==,type:str]
    mac_only_encrypted: true
    unencrypted_suffix: _unencrypted
    version: 3.13.0
